name: 📝 PR Build Docs
on:
  pull_request:
    paths:
      - '.github/workflows/docs-pr-build.yml'
      - 'docs/**'

defaults:
  run:
    working-directory: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run build
